CREATE DATABASE IF NOT EXISTS store;

USE store;

DROP TABLE IF EXISTS users;
DELIMITER |
CREATE TABLE IF NOT EXISTS users (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL, 
    province VARCHAR(20) NOT NULL, 
    email VARCHAR(100) NOT NULL, 
    date_joined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
